# Generated by Django 4.2.2 on 2025-07-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_coursecategory_remove_video_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
